export let  CARDFETCHING = 'CARDFETCHING'
export let CARDFETCHINGSUCCSESS = 'CARDFETCHINGSUCCSESS'
export let CARDFETCHINGERROR = 'CARDFETCHINGERROR'
export const SETCARDSPAGE = 'SETCARDSPAGE'
export const ADD_TO_BASKET = 'ADD_TO_BASKET'

